modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/VeinMining/issues"
logoFile="veinmining_icon.png"
logoBlur=false
[[mods]]
modId="veinmining"
version="${version}"
displayName="Vein Mining"
displayURL="https://github.com/TheIllusiveC4/VeinMining"
authors="C4"
description='''
A lightweight, highly configurable Vein Mining enchantment for tools.
'''
[[dependencies.veinmining]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.veinmining]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
